services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile

    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile

    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge