- hosts: frontend
  become: yes
  vars_files:
    - vault.yml
    - frontend_vars.yml
  tasks:
    - name: Update apt cache and upgrade
      apt: update_cache=yes upgrade=dist

    - name: Install Node.js 23, git, curl, Caddy
      apt:
        name:
          - git
          - curl
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
        state: present

    - name: Add Node.js 23.x repo
      shell: curl -fsSL https://deb.nodesource.com/setup_23.x | bash -
      args:
        warn: false

    - name: Install Node.js
      apt: name=nodejs state=present

    - name: Install Caddy
      apt:
        deb: https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_linux_amd64.deb

    - name: Install pnpm and pm2 globally
      npm:
        name: "{{ item }}"
        global: yes
      loop:
        - pnpm
        - pm2

    - name: Clone repository
      git:
        repo: 'https://github.com/hammadmajid/CodeAlpha_MiniSocialMediaApp.git'
        dest: /opt/mini-social-app
        version: main

    - name: Create client .env
      copy:
        dest: /opt/mini-social-app/apps/client/.env
        content: |
          API_BASE_URL=http://{{ backend_private_ip }}:3000
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Install dependencies
      shell: pnpm install
      args:
        chdir: /opt/mini-social-app

    - name: Build client
      shell: pnpm build --filter=client
      args:
        chdir: /opt/mini-social-app

    - name: Start frontend with PM2
      shell: pnpm run start
      args:
        chdir: /opt/mini-social-app/apps/client

    - name: Save PM2 process list
      shell: pm2 save

    - name: Setup PM2 startup
      shell: pm2 startup systemd -u ubuntu --hp /home/ubuntu

    - name: Configure Caddyfile
      copy:
        dest: /etc/caddy/Caddyfile
        content: |
          pubment.xyz {
            reverse_proxy localhost:3000
            encode gzip
            header {
              Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
              X-Content-Type-Options "nosniff"
              X-Frame-Options "DENY"
              X-XSS-Protection "1; mode=block"
              Referrer-Policy "no-referrer-when-downgrade"
            }
            @http {
              protocol http
            }
            redir @http https://{host}{uri}
          }
        owner: root
        group: root
        mode: '0644'

    - name: Restart Caddy
      service:
        name: caddy
        state: restarted
        enabled: yes