---
- hosts: all
  become: yes
  tasks:
    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      with_items:
        - mini-social-server
        - mini-social-client
      ignore_errors: yes

    - name: Remove containers
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - mini-social-server
        - mini-social-client
      ignore_errors: yes

    - name: Remove Docker images
      docker_image:
        name: "{{ item }}"
        state: absent
      with_items:
        - mini-social-server
        - mini-social-client
      ignore_errors: yes

    - name: Clean up application directory
      file:
        path: /opt/mini-social-app
        state: absent
      ignore_errors: yes

    - name: Clean up environment files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /opt/mini-social-app/.env
        - /opt/mini-social-app/apps/client/.env
      ignore_errors: yes

- hosts: frontend
  become: yes
  tasks:
    - name: Stop Caddy service
      service:
        name: caddy
        state: stopped
      ignore_errors: yes

    - name: Remove Caddy configuration
      file:
        path: /etc/caddy/Caddyfile
        state: absent
      ignore_errors: yes

    - name: Restart Caddy with default config
      service:
        name: caddy
        state: started
      ignore_errors: yes